### PR TITLE
Rely on getOwner polyfill

### PR DESCRIPTION
**Pull request by xomaczar**
To support ember < 2.3.0 projects, we should rely on getOwner polyfill

### CODE REVIEW

**Comment by blimmer** [comment]
This looks good to me. We should also add an ember-try config for ember 1.13.x at some point.

**Comment by blimmer** [comment]
@xomaczar , can you please add an ember pre 2.4 to the ember-try and travis config to ensure that this works as expected?

**Comment by xomaczar** [comment]
@blimmer Sorry I was out of town. I've upgrade ember-try to the latest version and changed ember versions we are testing against. It now goes all the way back to 1.13.13 - see travis output for more info.

**Comment by blimmer** [comment]
Looks great to me. @rlivsey will you please review when you have a second?

**Comment by xomaczar** [comment]
ping @rlivsey @blimmer

**Comment by blimmer** [comment]
@rlivsey will need to merge this - I don't have merge or publish rights on this repo.

**Comment by rlivsey** [comment]
Thanks! Sorry for my tardiness, I've been snowed under and dropped the ball a bit!

**Comment by rlivsey** [comment]
Released as 0.8.1

**Comment by xomaczar** [comment]
Thanks

**Pull request merged**
