### PR TITLE
Make resolver import work for 1.13 and 2.2 ember-cli apps.

### LINKED ISSUE #32: 0.7.1 resolver breaks 1.13.x app
Getting this issue with 0.7.1 on 1.13.x app:

```
not ok 60 PhantomJS 2.0 - TestLoader Failures cs/tests/acceptance/error-test: could not be loaded
    ---
        message: >
            Could not find module `ember-resolver` imported from `cs/initializers/setup-ember-can`
        stack: >
            	at missingModule (http://localhost:7357/assets/vendor.js:177:93)
            	at findModule (http://localhost:7357/assets/vendor.js:192:30)
            	at reify (http://localhost:7357/assets/vendor.js:128:32)
            	at build (http://localhost:7357/assets/vendor.js:146:28)
            	at findModule (http://localhost:7357/assets/vendor.js:194:14)
            	at requireModule (http://localhost:7357/assets/vendor.js:181:22)
            	at http://localhost:7357/assets/vendor.js:70968:33
            	at forEach ([native code])
            	at default (http://localhost:7357/assets/vendor.js:70965:19)
            	at http://localhost:7357/assets/cs.js:132:41
            	at exports (http://localhost:7357/assets/vendor.js:96:39)
            	at build (http://localhost:7357/assets/vendor.js:146:17)
            	at findModule (http://localhost:7357/assets/vendor.js:194:14)
            	at reify (http://localhost:7357/assets/vendor.js:128:32)
            	at build (http://localhost:7357/assets/vendor.js:146:28)
            	at findModule (http://localhost:7357/assets/vendor.js:194:14)
            	at reify (http://localhost:7357/assets/vendor.js:128:32)
            	at build (http://localhost:7357/assets/vendor.js:146:28)
            	at findModule (http://localhost:7357/assets/vendor.js:194:14)
            	at requireModule (http://localhost:7357/assets/vendor.js:181:22)
            	at require (http://localhost:7357/assets/test-loader.js:60:16)
            	at loadModules (http://localhost:7357/assets/test-loader.js:51:25)
            	at load (http://localhost:7357/assets/test-loader.js:82:35)
            	at http://localhost:7357/assets/test-support.js:15143:20
        Log: |
```

### PR DESCRIPTION
**Pull request by rwjblue**
Fixes #32

### CODE REVIEW

**Comment by rwjblue** [comment]
Failure in beta channel is due to ember-inject-owner feature changes.

**Comment by rlivsey** [comment]
:+1: many thanks!

I'll take a look at the ember-inject-owner stuff shortly, I've another couple of addons that's affecting too.

**Comment by rlivsey** [comment]
Released as v0.7.2

**Comment by blimmer** [comment]
Thank you @rwjblue , really appreciate your help.

**Comment by rlivsey** [comment]
Hmm I'm still getting deprecation warnings in my app. 

`requirejs.entries['ember-resolver']` is undefined, but I see theres an entry for `ember-resolver/index`

@rwjblue should this be checking for `ember-resolver/index` too / instead?

**Comment by rwjblue** [comment]
Yessir

**Comment by rwjblue** [comment]
My fault, we should call `if (requirejs.entries['ember-resolver'] || requirejs.entries['ember-resolver/index']) {` instead of what I did

**Comment by rlivsey** [comment]
No worries, I've just released v0.7.3 with that change - thanks again!

**Pull request merged**
