### PR TITLE
Fix peerDependency from `ember-source`

### PR DESCRIPTION
**Pull request by mkszepp**
I have forgot to update the peerDependency in `package.json`

### CODE REVIEW

**Comment by mkszepp** [comment]
@RobbieTheWagner thanks for merging everything... do you have any plan, what we should do as next? Is there any roadmap to next major, what we should do?

**Review by RobbieTheWagner — APPROVED** [review]

**Comment by RobbieTheWagner** [comment]
@mkszepp no plans, I think updating all this is probably all we need.

**Comment by mkszepp** [comment]
@RobbieTheWagner okay that sound good... the only thing what i would like to do, before we are making the release is, exporting the normalize util private. I will look to make a PR in next days

**Comment by RobbieTheWagner** [comment]
Sounds good @mkszepp!

**Pull request merged**
