### PR TITLE
Convert to V2 addon

### LINKED ISSUE #159: Interested moving to a V2 addon ?
Hello,

Do you need help moving this package to a V2 addon format ? I've noticed this repository isn't very active, so I'd be happy to help upgrade the package.

### PR DESCRIPTION
**Pull request by mkszepp**
Now, as we have a modern app, its time to move to an addon V2 ([RFC](https://rfcs.emberjs.com/id/0507-embroider-v2-package-format/))

Changes:
- convert addon to v2 (using addon-blueprint)
- convert helpers to TS
- add template registry
- replace model type to simple object
- Modify `instanceof` check (caused by ember-auto-import bug see below)

Braking changes:
- removing initializer (see comment below)

When this changes are landed we should do:
- drop ember < 3.28
- removing codes deprecation like 'can' service & `computed.js` (after that, the addon is typed)

close #159

### CODE REVIEW

**Comment by mkszepp** [comment]
We are running in this issue: https://github.com/embroider-build/ember-auto-import/issues/588
To make a simple workaround while this will be fixed i have checked if there are existing necessary functions... see commit https://github.com/minutebase/ember-can/pull/166/commits/d0bd2facc33a0b5a58304d032722f2491d54de02

**Review by esbanarango — APPROVED** [review]

**Review by RobbieTheWagner — APPROVED** [review]

**Comment by RobbieTheWagner** [comment]
@mkszepp thanks for your work on this! Can you elaborate on if there are actual breaking changes in this? If we think the initializer was not needed, then is this actually breaking? Are we dropping node or Ember versions or changing anything major here? I want to make sure we label the PR correctly.

**Comment by charlesfries** [comment]
We are also losing the ability blueprints with this PR. I recall reading that blueprints aren't even compatible with V2 addons, but maybe something to mention in the release

**Comment by mkszepp** [comment]
Ups... blueprint we ca readd... the convert script has maybe not implemented to copy into right place..
I will readd the blueprints... thanks for info

**Comment by mkszepp** [comment]
blueprints were readded... they are working like before... no braking changes

**Comment by mkszepp** [comment]
blueprints are now in TS... when consumer app has `"isTypeScriptProject": true` in `.ember-cli` they will be created as TS, otherwise they will transformed into JS

**Comment by mkszepp** [comment]
one thing what we should do (let me know if we want do it here or later in an other PR)...

`ability-test` are checking atm if `ember-cli-mocha` or `ember-cli-qunit` are installed... Both packages are deprecated since 2019 and replaced with `ember-mocha` / `ember-qunit`...
Looking to RFC `ember-mocha` is also already depreacted see https://rfcs.emberjs.com/id/0858-deprecate-ember-mocha/

So i think, we should make blueprint changes braking and allow only `ember-qunit`... what do you think?

https://github.com/minutebase/ember-can/blob/d075697ed7c8c34dc64494374291148f74ce816e/blueprints/ability-test/index.js#L6-L21

**Comment by RobbieTheWagner** [comment]
@mkszepp I agree we should only support `ember-qunit`. So you think there are no breaking changes for this PR? Just trying to decide on a label.

**Comment by RobbieTheWagner** [comment]
> @RobbieTheWagner no its braking, because we have removed `initializer` that is possible braking for old `ember-inflector`.

But I thought you said the initializer was doing nothing? If it was not needed before, I wouldn't consider that breaking.

**Comment by mkszepp** [comment]
> But I thought you said the initializer was doing nothing? If it was not needed before, I wouldn't consider that breaking.
Yes it looks so...
So this PR is not braking

**Comment by RobbieTheWagner** [comment]
Okay, I marked as enhancement and merged. Thanks for the PR!

**Pull request merged**
