### PR TITLE
feat: refactor Ability to ES6 Class

### PR DESCRIPTION
**Pull request by Gorzas**
Related #138

### CODE REVIEW

**Comment by Exelord** [comment]
We are going to switch away form EmberObject :) Happy to go one step further. 

Also, I just merged a PR with updates #142. Could you rebase yours?

**Comment by Gorzas** [comment]
Thanks @Exelord. I'll rebase my code this afternoon 😄 . Also, I'll take a look to the EmberObject requirement, I'll keep you informed with anything I go forward.

**Comment by Gorzas** [comment]
@Exelord rebase done with the latest changes. Now there shouldn't be any conflicts 😄  but there are some [linter problems](https://github.com/minutebase/ember-can/pull/144/checks?check_run_id=2944161620).

**Comment by Gorzas** [comment]
I've fixed the linter problems but now I'm having the following error (I believe it's related to the last release of Ember.js):

```
[ember-auto-import] this version of ember-auto-import requires the app to have a dependency on webpack 
```

**Comment by derrabauke** [comment]
Can we haz this? :smiley_cat:

**Comment by charlesfries** [comment]
Looks like this work is already completed on the main branch. Possibly can close this PR

**Pull request closed without merging**
