### PR TITLE
Fix ember-getowner-polyfill deprecation.

### PR DESCRIPTION
**Pull request by blimmer**

### CODE REVIEW

**Comment by f3anaro** [comment]
Will there be a new release for this, maybe `v0.8.2`? :)

**Comment by blimmer** [comment]
I don't have npm publish on this repo. You'll need to ping @rlivsey

**Comment by rlivsey** [comment]
I'll get onto this ASAP, been ridiculously busy lately so been ignoring the 'hub a bit.

@blimmer do you know if it's possible to add someone else to be able to publish to NPM too, without an organisation etc…?

**Comment by blimmer** [comment]
Yep, you could add me just as an npm user without anything to do with the organization, etc.

```
npm owner add blimmer ember-can
```

**Comment by rlivsey** [comment]
@blimmer neat, I've done that so hopefully you'll be able to cut a new release if you want to give that a go!

**Comment by blimmer** [comment]
Awesome - thanks @rlivsey . @f3anaro , v0.8.2 is available now on npm.

**Comment by f3anaro** [comment]
@blimmer Awesome! You are rocket fast! :D

**Pull request merged**
