### PR TITLE
Migrate blueprint to ES6 class

### LINKED ISSUE #92: Update blueprints to ES6 classes
What do you think about updating the blueprints to use ES6 classes? Or is it soon?

So instead generating the old syntax, the blueprint generates something like this:

```
import { Ability } from 'ember-can';

export default class extends Ability {
}
```

Maybe we can add an option so the developer can choose between the version they prefer, something like it's been doing with the blueprints of ember source.

### PR DESCRIPTION
**Pull request by Gorzas**
Close #92

### CODE REVIEW

**Comment by Gorzas** [comment]
It's important to notice that they may be some caveats using ES6 classes. Anyway, we are using this type of blueprint on our current projects (working on production) and we haven't found anything buggy yet.

**Comment by Exelord** [comment]
Native classes are only supported from ember 3.6. We need to provide wider support :/

**Comment by Gorzas** [comment]
@Exelord Ok, maybe we can do something to choose the blueprint depending on the Ember version? I think there're other libraries that do it. Do you know a way to do it?

**Comment by Gorzas** [comment]
I float this merge request as ember-can now requires Ember 3.8 and above. Can we have this merge request accepted o should I close it?

**Comment by Exelord** [comment]
Yep :) Thank you for bringing it up once more! <3

**Pull request merged**
