### PR TITLE
New Abilities concept, auto-tracking support

### PR DESCRIPTION
**Pull request by Exelord**
A draft of the future

### CODE REVIEW

**Comment by charlesfries** [comment]
Anything I can do to help get this merged?

**Comment by derrabauke** [comment]
What is left to do with this? Need help?

**Comment by abel-n** [comment]
I'm also interested in the resolution, `ember-classic-decorator` needs to be removed from our project and this is blocking. Need help? :slightly_smiling_face:

**Comment by Exelord** [comment]
Unfortunately I don't have a time currently to develop this project further.

**Comment by sacarino** [comment]
@Exelord are you open to adding other maintainers?

**Comment by Exelord** [comment]
I am not the owner of this repo :)

**Pull request closed without merging**
